In [1]:
import numpy as np

## Datatypes and Attributes

In [5]:
a1 = np.array([1,2,3])
a1,type(a1)

(array([1, 2, 3]), numpy.ndarray)

In [8]:
a2 = np.array([[1,2,3],
               [4,5,6]])
a2, type(a2)

(array([[1, 2, 3],
        [4, 5, 6]]),
 numpy.ndarray)

In [19]:
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8.1,9]],
               [[10,11,12],
               [13,14,15],
               [16,17,18]]])
a3, type(a3)

(array([[[ 1. ,  2. ,  3. ],
         [ 4. ,  5. ,  6. ],
         [ 7. ,  8.1,  9. ]],
 
        [[10. , 11. , 12. ],
         [13. , 14. , 15. ],
         [16. , 17. , 18. ]]]),
 numpy.ndarray)

In [14]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [17]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [20]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('int32'), dtype('float64'))

In [21]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [22]:
import pandas as pd

In [24]:
a3_p = pd.DataFrame(a2)
a3_p

0  1  2
0  1  2  3
1  4  5  6

In [26]:
sample_array = np.array([1,2,3])
sample_array, type(sample_array)

(array([1, 2, 3]), numpy.ndarray)

In [30]:
ones = np.ones((2,3))

In [32]:
ones.dtype

dtype('float64')

In [33]:
zeros = np.zeros((2,2,2))
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [35]:
range_array = np.arange(0,100,10)
range_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
random_array = np.random.randint(0,10,size = (4,4))
random_array, random_array.size, random_array.shape

(array([[8, 4, 2, 7],
        [8, 8, 5, 8],
        [3, 9, 8, 1],
        [6, 2, 2, 1]]),
 16,
 (4, 4))

In [39]:
random_array_2 = np.random.random((4,4))

In [41]:
random_array_2

array([[0.62758921, 0.90007065, 0.39992771, 0.08857591],
       [0.40426097, 0.56375206, 0.8487984 , 0.88293598],
       [0.61734196, 0.00313354, 0.93089601, 0.97263375],
       [0.97583509, 0.42364689, 0.09522086, 0.55231427]])

In [110]:
np.random.seed(seed=70)
random_array_3 = np.random.randint(1,70,size=(5,5))
random_array_3

array([[25, 61, 60,  1, 53],
       [24, 53,  2, 17, 42],
       [57, 22, 48, 61, 16],
       [11, 64, 12, 36, 35],
       [42, 35, 14,  7,  9]])

#### Viewing Arrays and Matrices

In [111]:
len(np.unique(random_array_3))

21

#### Manipulating

In [113]:
a1

array([1, 2, 3])

In [114]:
a2 = np.arange(4,7)
a2

array([4, 5, 6])

In [117]:
a1 + a2 

array([5, 7, 9])

In [118]:
a1- a2

array([-3, -3, -3])

In [119]:
a1 / a2

array([0.25, 0.4 , 0.5 ])

In [120]:
a1 // a1

array([1, 1, 1], dtype=int32)

In [121]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [122]:
np.log(a2)

array([1.38629436, 1.60943791, 1.79175947])

In [123]:
a1 * a2

array([ 4, 10, 18])

In [124]:
a2 * a1

array([ 4, 10, 18])

In [126]:
a5 = np.arange(6).reshape(2,3)

In [127]:
a1 * a5

array([[ 0,  2,  6],
       [ 3,  8, 15]])

In [128]:
a5 * a1

array([[ 0,  2,  6],
       [ 3,  8, 15]])

#### Aggretation

In [138]:
massive_array = np.random.random(100000)
massive_array[:20]

array([0.03980982, 0.69643316, 0.51652477, 0.56616603, 0.3666892 ,
       0.37966509, 0.56710266, 0.79515598, 0.8344402 , 0.39314631,
       0.74226392, 0.06310504, 0.68960086, 0.9947633 , 0.16678786,
       0.80734241, 0.46311395, 0.87834265, 0.03384425, 0.8368539 ])

In [139]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

12.7 ms ± 394 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
39.1 µs ± 1.03 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [140]:
np.mean(massive_array)

0.4991760163018505

In [142]:
massive_array.mean()

0.4991760163018505

In [143]:
np.max(massive_array)

0.999986875804551

In [144]:
np.mean(massive_array)

0.4991760163018505

In [146]:
np.std(massive_array)

0.2882449109658513

In [147]:
np.var(massive_array)

0.08308512869771154

In [148]:
np.sqrt(np.var(massive_array))

0.2882449109658513

In [149]:
h_var = np.array([1,2,100,1000,9897])
l_var = np.array([1,2,3,4,4])

In [150]:
np.std(h_var), np.std(l_var)

(3866.797486292759, 1.16619037896906)

In [151]:
np.var(h_var), np.var(l_var)

(14952122.8, 1.3599999999999999)

In [152]:
%matplotlib inline
import matlplotlib.pyplot as mlt
plt.hist(h_var)
plt.show()

ModuleNotFoundError: No module named 'matplotlib'